-- =============================================================================
-- ESQUEMA RELACIONAL SQL - PROTHERA RISK & HR COMPLIANCE (H2 / ANSI SQL)
-- =============================================================================

CREATE TABLE IF NOT EXISTS funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    salario DECIMAL(15, 2) NOT NULL,
    funcao VARCHAR(50) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_func_nome ON funcionarios(nome);
CREATE INDEX IF NOT EXISTS idx_func_funcao ON funcionarios(funcao);
CREATE INDEX IF NOT EXISTS idx_func_data_nasc ON funcionarios(data_nascimento);

CREATE OR REPLACE VIEW view_risco_folha_funcao AS
SELECT 
    funcao,
    COUNT(id) AS total_colaboradores,
    SUM(salario) AS custo_total_funcao,
    AVG(salario) AS salario_medio_funcao,
    MIN(salario) AS salario_minimo_funcao,
    MAX(salario) AS salario_maximo_funcao
FROM funcionarios
GROUP BY funcao;
